version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    target-branch: development
    labels:
      - "dependabot"
    schedule:
      interval: daily
    commit-message:
      prefix: "[DEPENDABOT]"